name: CI

on:
  push:
    branches: [ main, v3 ]
  pull_request:
    branches: [ main, v3 ]

jobs:
  # TODO: separate build and test jobs
  # TODO: do a matrix build for alpine
  # TODO: check and update to latest action versions
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create config files
      run: |
        cp config.yaml.example config.yaml

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out
